### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cgrinaldi**

### CODE REVIEW

**Comment by cgrinaldi** [comment]
So this is an example of a Pull Request that I made. Here we can have a discussion about code, best practices, etc. 

If you look at Waffle, by creating a PR, a new issue has been moved to the "In Progress" section.

**Comment by nrbontha** [comment]
This is a comment.

**Comment by cgrinaldi** [comment]
Nice! So here is where we could potentially have a conversation about whatever the code submitted is (also known as a PR). 

Once that green button that says "Merge pull request" is pushed, the code gets merged into our group's codebase.

However, this will be different then your fork, so you will want to pull those changes in. To do that, do the following

```
git remote add upstream <url-to-KaggleCompetitions/AfricanSoil>
git pull upstream master (in your master branch)
git push origin master (to push to your remote)
```

And that should hopefully update both your local and remote repos.

**Comment by nrbontha** [comment]
So, the first two commands work, but the last one does not. 

If I try to push to the origin master, I get these errors:
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository

**Comment by cgrinaldi** [comment]
Try typing `git remove -v`, that will show you all of the remote repos that you have tied to your local repo. Once you do that, copy and paste the result here.

**Comment by nrbontha** [comment]
It lists the URL twice:
upstream https://github.com/KaggleCompetitions/AfricanSoil (fetch)
upstream https://github.com/KaggleCompetitions/AfricanSoil (push)

**Comment by cgrinaldi** [comment]
Not sure where your origin went, but run the following command:

`git remote add origin https://github.com/nrbontha/AfricanSoil.git`

That should add the origin repo, and allow you to then run `git push origin master`.

**Pull request merged**
